# database
spring:
  datasource:
    url: jdbc:mysql://plong.cox1oouznzgl.ap-southeast-2.rds.amazonaws.com:3306/plong_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: young0825
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

